service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: nforu-goe-mypage-xqlbyutclt
  name: nforu-goe-mypage-xqlbyutclt
  selector: nforu-goe-mypage-xqlbyutclt
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-nforu-goe-mypage-xqlbyutclt
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: nforu-goe-mypage-xqlbyutclt
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: nforu-goe-mypage-xqlbyutclt
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: nforu-goe-mypage-xqlbyutclt
    port: 8080
  volume:
    name: pvc-nforu-goe-mypage-xqlbyutclt
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    mysql:
      name: secret-goe-database-v0hw8yrxp1
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-nforu-goe-mypage-xqlbyutclt
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
