service:
  port:
    name: http
    l4_protocol: TCP
    port: 8761
    targetPort: 8761
  label: nforu-msa-eurekaserver-3c9mxqjavw
  name: nforu-msa-eurekaserver-3c9mxqjavw
  selector: nforu-msa-eurekaserver-3c9mxqjavw
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-nforu-msa-eurekaserver-3c9mxqjavw
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: nforu-msa-eurekaserver-3c9mxqjavw
    type: egov-springcloud-discovery
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: nforu-msa-eurekaserver-3c9mxqjavw
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: nforu-msa-eurekaserver-3c9mxqjavw
    port: 8761
  volume:
    name: pvc-nforu-msa-eurekaserver-3c9mxqjavw
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-nforu-msa-eurekaserver-3c9mxqjavw
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
